function [ edge_score_matrix ] = filter_multiclass_output(relationships, edge_str, edge_score_matrix, root, search_description)
%UNTITLED2 Mask parts of edge_score_matrix according to manual filters
%   Detailed explanation goes here
   
    data = load(sprintf('%s/Flickr_concepts/%s_analysis.mat', root, search_description));
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'PartOf', 'HasA', 'IsA', 'AtLocation', 'CreatedBy', 'MadeOf', 'LocatedNear', 'SimilarSize'}, ...
        'pos_N', false, ...
        'pos_N', false);
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'CapableOf', 'ReceivesAction'}, ...
        'pos_N', false, ...
        'pos_V', false);
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'HasProperty'}, ...
        'pos_N', false, ...
        'pos_A', false);
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'UsedFor'}, ...
        'pos_N', false, ...
        'pos_A', true);
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'LocationOfAction'}, ...
        'pos_V', false, ...
        'pos_N', false);
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'HasProperty'}, ...
        'isColor', true, ...
        '', false);
    
    [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
        {'PartOf', 'AtLocation'}, ...
        'isLocation', true, ...
        'isLocation', true);
    
%     [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
%         {'GeographicContainment'}, ...
%         'isLocation', false, ...
%         'isLocation', false);
%     
%     [edge_score_matrix] = filter_pos_edges(data, edge_score_matrix, edge_str, relationships, ...
%         {'AtLocationGeographic'}, ...
%         'pos_N', false, ...
%         'isLocation', false);
 
end

