function [result, error_rates] = summerize_error(root, search_description, classifier_type, ...
    multi_class_scores, multi_class_ground_truth, relations_str, tags_str, ...
    ground_truth_str, numberImages, numberOwners, metrics, metric_str, use_threshold)
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

[recall, precision, accuracy, misclassified, misclassified_3, unlabeled, labels, ...
    sorted_score] = multi_class_analysis(multi_class_scores, multi_class_ground_truth, ...
    use_threshold, relations_str, sprintf('%s\\transfer\\%s_%s', root, search_description, classifier_type));

%Mean precision and recall
m_recall_at_one = mean(recall(1, ~isnan(recall(1,:))));
m_precision_at_one = mean(precision(1, ~isnan(precision(1,:))));
m_recall_at_three = mean(recall(3, ~isnan(recall(3,:))));
m_precision_at_three = mean(precision(3,~isnan(precision(3,:))));

display(sprintf('%s:\tPercent of edges with a correct label: %f \n\t\t\tMean Recall at 1: %f\n\t\t\tMean Precision at 1: %f\n\t\t\tMean Recall at 3: %f\n\t\t\tMean Precision at 3: %f', ...
    classifier_type, accuracy, m_recall_at_one, m_precision_at_one, m_recall_at_three, m_precision_at_three)); 

error_rates = [accuracy, m_recall_at_one, m_precision_at_one, m_recall_at_three, m_precision_at_three];

relations_str = [{' '}; relations_str];
labels = labels + 1;
result = [[{'Tag1', 'Tag2', 'Labeled Relationship1', 'Score1', ...
    'Labeled Relationship2', 'Score2', 'Labeled Relationship3', 'Score3', ...
    'Ground Truth Relationship', 'InTopThree', 'IsMisclassified', ...
    'IsUnlabeled', 'Number of Images', 'Number of Owners'} metric_str]; ...
    tags_str, ...
    relations_str(labels(:,1)), ...
    num2cell(full(sorted_score(:, 1))), relations_str(labels(:,2)), ...
    num2cell(full(sorted_score(:, 2))), relations_str(labels(:,3)), ...
    num2cell(full(sorted_score(:, 3))), ground_truth_str(:), ...
    num2cell(double(misclassified_3)), ...
    num2cell(double(misclassified)), ...
    num2cell(double(unlabeled)), ...
    num2cell(full(numberImages)), ...
    num2cell(full(numberOwners)), ...
    num2cell(full(metrics))];
end

