%Global Variables
IS_FREEBASE = 7;
IS_CONCEPTNET = 8;
IS_LEMMA = 9;
IS_SYNONYM = 10;
IS_TRANSLATION = 12;
IS_ALIAS = 14;
NUM_IMAGES = 1;
NUM_OWNERS = 11;
PROB = 2;
PMI = 3;
MIN_COND_PROB = 4;
MEAN_COND_PROB = 5;
COND_PROB = 6;
N_PMI = 13;
MAX_DIM = 14;